### ISSUE TITLE
Add a `CNAME` DNS record for the `homemaker.transitionbydesign.org` hostname pointing to `transitionbydesign.github.io` 

### ISSUE THREAD

**Issue by wu-lee** [TransitionbyDesign/homemaker#22]
As per [docs here][1]

[1]: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

**Comment by wu-lee** [comment]
Note: you can host the site on a `transitionbydesign.org` subdomain, say `homemaker.transitionbydesign.org` for no extra cost.

How exactly you do that depends on who is hosting the domain registration/management for you, but typically you log onto their website and add a new CNAME record for the subdomain which references `transitionbydesign.github.io`, as per the docs linked above.

If you do decide to buy a new domain, say `homemaker-oxford.org` and want to host it on that (and not a subdomain) the recipe is slightly different, as the docs say (simplifying) you need to create A records for this domain to the GitHub pages IP addresses (there are several):

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

Finally, if you also want `www.homemaker-oxford.org` to work, you need to do the CNAME step for that subdomain.

In all cases, if you get the option to set the `TTL` (time-to-live) field for these records, set it to something low-ish initially, like 36000 (seconds, i.e. 10 minutes). This means a mistake can be fixed in about 10 minutes, rather than the more usual 1 day.

There are some other steps but I can do those.

Background info:
- https://support.dnsimple.com/articles/cname-record/
- https://support.dnsimple.com/articles/a-record/
- https://support.dnsimple.com/articles/alias-record/
- https://support.dnsimple.com/articles/what-minimum-time-to-live/

**Comment by Charlie-TbD** [comment]
Hey - bought the domain homemakeroxford.org and changed the DNS settings. I'll have a better look at this later but I will make you a contributer on our godaddy account in case you need to do any changes there.

![image](https://user-images.githubusercontent.com/72264494/95856629-969cac80-0d5a-11eb-9b21-f4299fc4f6f5.png)

**Comment by wu-lee** [comment]
Thanks Charlie - I've hooked it up now so you should be able to see the current demo there.

https://homemakeroxford.org/

It's getting closer, still dummy content however, and a few more styling touches to add.
